spring:
  application:
    name: security
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: security
    password: 123456
    driver-class-name: org.postgresql.Driver  # Optional, Spring Boot can auto-detect
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect